/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as TimetableReviewRouteImport } from './routes/timetable.review'
import { Route as TimetableUploadRouteImport } from './routes/timetable.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableReviewRoute = TimetableReviewRouteImport.update({
  id: '/timetable/review',
  path: '/timetable/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableUploadRoute = TimetableUploadRouteImport.update({
  id: '/timetable/upload',
  path: '/timetable/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/timetable/review': typeof TimetableReviewRoute
  '/timetable/upload': typeof TimetableUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/timetable/review': typeof TimetableReviewRoute
  '/timetable/upload': typeof TimetableUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/requests': typeof RequestsRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/timetable/review': typeof TimetableReviewRoute
  '/timetable/upload': typeof TimetableUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/requests'
    | '/signup'
    | '/verify'
    | '/matches/$matchId'
    | '/timetable/review'
    | '/timetable/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/requests'
    | '/signup'
    | '/verify'
    | '/matches/$matchId'
    | '/timetable/review'
    | '/timetable/upload'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/requests'
    | '/signup'
    | '/verify'
    | '/matches/$matchId'
    | '/timetable/review'
    | '/timetable/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RequestsRoute: typeof RequestsRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  TimetableReviewRoute: typeof TimetableReviewRoute
  TimetableUploadRoute: typeof TimetableUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/review': {
      id: '/timetable/review'
      path: '/timetable/review'
      fullPath: '/timetable/review'
      preLoaderRoute: typeof TimetableReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable/upload': {
      id: '/timetable/upload'
      path: '/timetable/upload'
      fullPath: '/timetable/upload'
      preLoaderRoute: typeof TimetableUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RequestsRoute: RequestsRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  TimetableReviewRoute: TimetableReviewRoute,
  TimetableUploadRoute: TimetableUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
